// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/(main)/page.info";
import * as MultimediaRoute from "@/app/(main)/[multimediaName]/page.info";

export const Home = makeRoute(
  "/(main)",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Multimedia = makeRoute(
  "/(main)/[multimediaName]",
  {
    ...defaultInfo,
    ...MultimediaRoute.Route
  }
);

